#ifndef VSCULPT_VBS_DEF_H
#define VSCULPT_VBS_DEF_H
#include <QObject>

class VbsDef : public QObject {
public:
	Q_OBJECT
public:
	enum BRUSH
	{
		BRUSH_INFLATE = 0,
		BRUSH_SNAKE_HOOK,
		BRUSH_CREASE,
		BRUSH_FLATTEN ,
		BRUSH_NUDGET ,
		BRUSH_CLAY_STRIP ,
		BRUSH_CLAY ,
		BRUSH_FILL ,
		BRUSH_ROTATE,
		BRUSH_DRAW,
		BRUSH_SMOOTH ,
		BRUSH_GRAB,
		BRUSH_THUMB,
		BRUSH_PINCH,
		BRUSH_TOTAL
	};
	Q_ENUMS(BRUSH);
	
	enum CURVE 
	{
		CURVE_SHARP,
		CURVE_SMOOTH,
		CURVE_ROUND,
		CURVE_ROOT,
		CURVE_TOTAL
	};
	Q_ENUMS(CURVE);

	enum MANIPULATOR_AXIS
	{
		MANIPULATOR_AXIS_0 = 1 << 0,
		MANIPULATOR_AXIS_1 = 1 << 1,
		MANIPULATOR_AXIS_2 = 1 << 2,
		MANIPULATOR_AXIS_FULL = MANIPULATOR_AXIS_0 | MANIPULATOR_AXIS_1 | MANIPULATOR_AXIS_2,
		MANIPULATOR_AXIS_NONE = 1 << 3
	};
	Q_ENUMS(MANIPULATOR_AXIS);

	enum MANIPULATOR_MODE
	{
		MANIPULATOR_SCALE,
		MANIPULATOR_ROTATE,
		MANIPULATOR_TRANSLATE,
		MANIPULATOR_NONE
	};
	Q_ENUMS(MANIPULATOR_MODE);

	enum RENDER_MODE
	{
		RENDER_SHADING,
		RENDER_WIREFRAME
	};
	Q_ENUMS(RENDER_MODE);

	enum BOOLEAN_TYPE
	{
		BOOLEAN_UNION,
		BOOLEAN_DIFFERENCE,
		BOOLEAN_INTERSECTION,
		BOOLEAN_NONE
	};
	Q_ENUMS(BOOLEAN_TYPE);

};
#endif